package org.hippo.toolkit.entity;

import java.io.Serializable;

/**
 * 用户信息表(t_user)数据实体类
 * <p>
 * Created by MyBatis Generator on 2017/08/19.
 */
public class UserVO extends BaseVO implements Serializable {

    /** serialVersionUID */
    private static final long serialVersionUID = 1L;

    /** 手机号(t_user.mobile) */
    private String mobile;

    /** 用户名(t_user.user_name) */
    private String userName;

    /** 用户密码(t_user.password) */
    private String password;

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated 2017/08/19
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", mobile=").append(mobile);
        sb.append(", userName=").append(userName);
        sb.append(", password=").append(password);
        sb.append("]");
        sb.append(", from super class ");
        sb.append(super.toString());
        return sb.toString();
    }
}